routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Middleware\ceklevel;

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();
Route::group(['middleware' => ['auth', 'ceklevel:admin,guru']], function (){
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('user', 'UserController')->except('destroy');
Route::resource('kelas', 'KelasController')->except('destroy');
Route::get('register', 'auth\RegisterController@showRegistrationForm')->name('register');
Route::get('/kelas/destroy/{id}', 'KelasController@destroy')->name('kelas.destroy');
Route::get('/user/destroy/{id}', 'UserController@destroy')->name('user.destroy');
Route::resource('siswa', 'SiswaController')->except('destroy');
Route::get('/siswa/destroy/{id}', 'SiswaController@destroy')->name('siswa.destroy');
});

app/siswa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class siswa extends Model
{
    protected $table = "siswas";
    protected $fillable = 
    ["nisn", 
    "body",
    "no_induk",
    "name",
    "tempat_lahir",
    "tanggal_lahir",
    "agama",
    "alamat",
    "no_hp_wali",
    "kelas_id"
    ];
    public function kelas(){
    return $this->belongsTo('App\Kelas');
    } 
}

app/Http/Controllers/SiswaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;
use App\siswa;
use App\Kelas;
use DataTables;
use DB;

class SiswaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $model = siswa::with('kelas');
        if ($request->ajax()) {
            $data = siswa::get();
            return Datatables::of($data)
                    ->addIndexColumn()
                    ->addColumn('Kelas',function (siswa $siswa) {
                        return $siswa->kelas->nama;})
                    ->addColumn('action', function($data){
                           $btn = '<a href="siswa/'.$data->id.'/edit" class="edit btn btn-success btn-sm">Edit</a> <a href="siswa/destroy/'.$data->id.'"  class="delete btn btn-danger btn-sm">Delete</a>';
                            return $btn;
                    })
                    ->rawColumns(['action'])
                    ->make(true);
        }
        return view('siswa.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $kelas = Kelas::all();
        return view('siswa.create', compact('kelas'));
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([ 
    		'nisn' => 'required',
    		'no_induk' => 'required',
            'name' => 'required',
    		'tempat_lahir' => 'required',
            'tanggal_lahir' => 'required',
    		'agama' => 'required',
            'alamat' => 'required',
    		'no_hp_wali' => 'required',
            'kelas_id' => 'required'
    	]);
        $post = new siswa;
        $post->nisn = $request["nisn"];
        $post->no_induk = $request["no_induk"];
        $post->name = $request["name"];
        $post->tempat_lahir = $request["tempat_lahir"];
        $post->tanggal_lahir = $request["tanggal_lahir"];
        $post->agama = $request["agama"];
        $post->alamat = $request["alamat"];
        $post->no_hp_wali = $request["no_hp_wali"];
        $post->kelas_id = $request["kelas_id"];
        $post->save();
        return redirect(route('siswa.index'))->with('success', 'Data Berhasil Di tambahkan');
    
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $siswa = siswa::find($id);
        return view('siswa.edit', ['siswa' => $siswa]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'nisn' => 'required',
    		'no_induk' => 'required',
            'name' => 'required',
    		'tempat_lahir' => 'required',
            'tanggal_lahir' => 'required',
    		'agama' => 'required',
            'alamat' => 'required',
    		'no_hp_wali' => 'required',
            'kelas_id' => 'required'
        ]);

        $siswa = siswa::find($id);
        $siswa->nisn = $request->nisn;
        $siswa->no_induk = $request->no_induk;
        $siswa->name = $request->name;
        $siswa->tempat_lahir = $request->tempat_lahir;
        $siswa->tanggal_lahir = $request->tanggal_lahir;
        $siswa->agama = $request->agama;
        $siswa->alamat = $request->alamat;
        $siswa->no_hp_wali = $request->no_hp_wali;
        $siswa->kelas_id = $request->kelas_id ;
        $siswa->update();
        Alert::success('Berhasil', 'Data Siswa Berhasil Di Perbaharui');
        
        return redirect(route('siswa.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $siswa = siswa::findOrFail($id);
        $siswa->delete();

        Alert::warning('Berhasil!', 'Data Berhasil Di Hapus');

        return redirect(route('siswa.index'));
    }
}

resources/views/siswa/create.blade.php
@extends('layouts.master')
@section('content')
<h2>Tambah Data</h2>
<div class="ml-3 mr-3">
    <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">Buat Data Siswa</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form  role="form" action="{{ route('siswa.store')}}" method="post">
        @csrf
          <div class="card-body">
            <div class="form-group">
              <label for="nisn">NISN</label>
              <input type="text" class="form-control" id="nisn" name="nisn" value="{{old('nisn')}}"  placeholder="Masukan Nama">
              @error('nisn')
              <div class="alert alert-danger">{{ $message }}</div>
              @enderror
            </div>
            <div class="form-group">
                <label for="nisn">NISN</label>
                <input type="text" class="form-control" id="nisn" name="nisn" value="{{old('nisn')}}"  placeholder="Masukan Nama">
                @error('nisn')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
              </div>
              <div class="form-group">
                <label for="no_induk">No Induk</label>
                <input type="text" class="form-control" id="no_induk" name="no_induk" value="{{old('no_induk')}}"  placeholder="Masukan No Induk">
                @error('no_induk')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
              </div>
              <div class="form-group">
                <label for="name">Nama</label>
                <input type="text" class="form-control" id="name" name="name" value="{{old('name')}}"  placeholder="Masukan Nama">
                @error('name')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
              </div>
              <div class="form-group">
                <label for="tempat_lahir">Tempat Lahir</label>
                <input type="text" class="form-control" id="tempat_lahir" name="tempat_lahir" value="{{old('tempat_lahir')}}"  placeholder="Masukan Tempat Lahir">
                @error('tempat_lahir')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
              </div>
              <div class="form-group">
                <label for="tanggal_lahir">Tanggal Lahir</label>
                <div class="input-group date" id='datetimepicker1'>
                    <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                    <input type="text" class="form-control" name="tanggal_lahir" id="tanggal_lahir" value="{{old('tanggal_lahir')}}" placeholder="yyyy/mm/dd">
                  </div>
                @error('tanggal_lahir')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
              </div>
              <div class="form-group">
                <label for="agama">Agama</label>
                <input type="text" class="form-control" id="agama" name="agama" value="{{old('agama')}}"  placeholder="Masukan Agama">
                @error('agama')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
              </div>
              <div class="form-group">
                <label for="alamat">NISN</label>
                <input type="text" class="form-control" id="alamat" name="alamat" value="{{old('alamat')}}"  placeholder="Masukan Alamat">
                @error('alamat')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
              </div>
              <div class="form-group">
                <label for="no_hp_wali">No HP Wali</label>
                <input type="text" class="form-control" id="no_hp_wali" name="no_hp_wali" value="{{old('no_hp_wali')}}"  placeholder="Masukan No HP Wali">
                @error('no_hp_wali')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
              </div>
              <div class="form-group">
                <label for="kelas_id">ID Kelas</label>
                <div class="col-md-6">
                  <select name="kelas_id" id="kelas_id" class="form-control"  class="form-control @error('kelas_id') is-invalid @enderror" value="{{ old('kelas_id') }}" required autocomplete="Kelas" autofocus>
                      <option value="" selected>---Pilih Kelas---</option>
                      @foreach ($kelas as $item)
                      <option value="{{$item->id}}">{{$item->nama}}</option>
                      @endforeach
                  </select>
                  <br>
                @error('kelas_id')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
              </div>
          <!-- /.card-body -->
    
          <div class="card-footer">
            <button type="submit" class="btn btn-primary">Create New</button>
          </div>
        </form>
      </div>
</div>
@endsection

resources/views/siswa/edit.blade.php
@extends('layouts.master')
@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('siswa.update', [$siswa->id]) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="nisn">NISN</label>
                            <input type="text" name="nisn" class="form-control" id="nisn" value="{{ $siswa->nisn }}"
                                placeholder="NISN.." autofocus>
                            @error('nisn')
                            <div class="alert alert-danger">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="no_induk">No Induk</label>
                            <input type="text" name="no_induk" class="form-control" id="no_induk" value="{{ $siswa->no_induk }}"
                                placeholder="No Induk.." autofocus>
                            @error('no_induk')
                            <div class="alert alert-danger">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="name">Nama</label>
                            <input type="text" name="name" class="form-control" id="name" value="{{ $siswa->name }}"
                                placeholder="Full Name.." autofocus>
                            @error('name')
                            <div class="alert alert-danger">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="tempat_lahir">Tempat Lahir</label>
                            <input type="text" name="tempat_lahir" class="form-control" id="tempat_lahir" value="{{ $siswa->tempat_lahir }}"
                                placeholder="Tempat Lahir.." autofocus>
                            @error('tempat_lahir')
                            <div class="alert alert-danger">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="tanggal_lahir">Tanggal Lahir</label>
                            <input type="text" name="tanggal_lahir" class="form-control" id="tanggal_lahir" value="{{ $siswa->tanggal_lahir }}"
                                placeholder="Tanggal Lahir.." autofocus>
                            @error('tanggal_lahir')
                            <div class="alert alert-danger">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="agama">Agama</label>
                            <input type="text" name="agama" class="form-control" id="agama" value="{{ $siswa->agama }}"
                                placeholder="Agama.." autofocus>
                            @error('agama')
                            <div class="alert alert-danger">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="alamat">Alamat</label>
                            <input type="text" name="alamat" class="form-control" id="alamat" value="{{ $siswa->alamat }}"
                                placeholder="Full Name.." autofocus>
                            @error('alamat')
                            <div class="alert alert-danger">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="no_hp_wali">No HP wali</label>
                            <input type="text" name="no_hp_wali" class="form-control" id="no_hp_wali" value="{{ $siswa->no_hp_wali }}"
                                placeholder="Full Name.." autofocus>
                            @error('no_hp_wali')
                            <div class="alert alert-danger">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="kelas_id">Kelas</label>
                            <input type="text" name="kelas_id" class="form-control" id="kelas_id" value="{{ $siswa->kelas_id }}"
                                placeholder="Kelas.." autofocus>
                            @error('kelas_id')
                            <div class="alert alert-danger">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        <button type="submit" class="btn btn-outline-primary float-right">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/siswa/index.blade.php
@extends('layouts.master')

@section('content')
<div class="container-fluid">
    {{-- flash Massage --}}
    @if (session('success'))
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{ session('success') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    @endif

    <table class="table table-hover data-table">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">NISN</th>
                <th scope="col">NO Induk</th>
                <th scope="col">Nama</th>
                <th scope="col">Tempat Lahir</th>
                <th scope="col">Tanggal Lahir</th>
                <th scope="col">Agama</th>
                <th scope="col">Alamat</th>
                <th scope="col">NO HP</th>
                <th scope="col">Kelas ID</th>
                <th scope="col">Kelas</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>

@push('script')
<script type="text/javascript">
    $(function () {
      
      var table = $('.data-table').DataTable({
          processing: true,
          serverSide: true,
          ajax: "{{ route('siswa.index') }}",
          columns: [
              {data: 'id', name: 'id'},
              {data: 'nisn', name: 'nisn'},
              {data: 'no_induk', name: 'no_induk'},
              {data: 'name', name: 'name'},
              {data: 'tempat_lahir', name: 'tempat_lahir'},
              {data: 'tanggal_lahir', name: 'tanggal_lahir'},
              {data: 'agama', name: 'agama'},
              {data: 'alamat', name: 'alamat'},
              {data: 'no_hp_wali', name: 'no_hp_wali'},
              {data: 'kelas_id', name: 'Kelas.name'},
              {data: 'Kelas', name: 'Kelas.name'},
              {data: 'action', name: 'action', orderable: false, searchable: false},
          ]
      });
      
    });
</script>
@endpush
@endsection