routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Middleware\ceklevel;

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();
Route::group(['middleware' => ['auth', 'ceklevel:admin,guru']], function (){
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('user', 'UserController')->except('destroy');
Route::resource('kelas', 'KelasController')->except('destroy');
Route::get('register', 'auth\RegisterController@showRegistrationForm')->name('register');
Route::get('/kelas/destroy/{id}', 'KelasController@destroy')->name('kelas.destroy');
Route::get('/user/destroy/{id}', 'UserController@destroy')->name('user.destroy');
Route::resource('siswa', 'SiswaController')->except('destroy');
Route::get('/siswa/destroy/{id}', 'SiswaController@destroy')->name('siswa.destroy');
});

app/Kelas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kelas extends Model
{
    protected $table = "kelas";
    protected $fillable = ['id','nama'];
    public function siswa()
    {
    return $this->hasMany('App\Siswa');
    } 
    // protected $fillable = ['id','nama'];

    public function User(){
        return $this->hasMany(User::class);
    }
    protected $guarded = [];
}

app/Http/Controllers/KelasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;
use DB;
use App\Kelas;
use DataTables;

class KelasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Kelas::get();
            return Datatables::of($data)
                    ->addIndexColumn()
                    ->addColumn('action', function($data){
     
                           $btn = '<a href="kelas/'.$data->id.'/edit" class="edit btn btn-success btn-sm">Edit</a> <a href="kelas/destroy/'.$data->id.'"  class="delete btn btn-danger btn-sm">Delete</a>';
                            return $btn;
                    })
                    ->rawColumns(['action'])
                    ->make(true);
        }
        
        return view('kelas.index');
    }


   

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('kelas.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([ 
            'name' => 'required',
        ]);

        $post = new Kelas;
        $post->nama = $request["name"];
        $post->save();
        
        Alert::success('Success!', 'Kelas Berhasil Di tambahkan');

        return redirect(route('kelas.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $kelas = Kelas::find($id);
        return view('kelas.edit', ['kelas' => $kelas]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'nama' => 'required'
        ]);

        $kelas = Kelas::find($id);
        $kelas->nama = $request->nama;
        $kelas->update();
        Alert::success('Berhasil', 'Data Kelas Berhasil Di Perbaharui');

        return redirect(route('kelas.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $kelas =  Kelas::findOrFail($id);
        $kelas->delete();

        Alert::warning('Berhasil!', 'Data Berhasil Di Hapus');

        return redirect(route('kelas.index'));
    }
}

resources/views/kelas/create.blade.php
@extends('layouts.master')

@section('content')
<div class="ml-3 mr-3">
    <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">Create New Cast</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form  role="form" action="{{ route('kelas.store')}}" method="post">
            @csrf
          <div class="card-body">
            <div class="form-group">
              <label for="nama">Nama Kelas</label>
              <input type="text" class="form-control" id="name" name="name" value="{{old('name')}}"  placeholder="Masukan Name">
              @error('name')
              <div class="alert alert-danger">{{ $message }}</div>
              @enderror
            </div>
          <!-- /.card-body -->
    
          <div class="card-footer">
            <button type="submit" class="btn btn-primary">Create New</button>
          </div>
        </form>
      </div>
</div>
@endsection

resources/views/kelas/edit.blade.php
@extends('layouts.master')
@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('kelas.update', [$kelas->id]) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" name="nama" class="form-control" id="name" value="{{ $kelas->nama }}"
                                placeholder="Full Name.." autofocus>
                            @error('name')
                            <div class="alert alert-danger">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        <button type="submit" class="btn btn-outline-primary float-right">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/kelas/index.blade.php
@extends('layouts.master')

@section('content')
<div class="container-fluid">
    {{-- flash Massage --}}
    @if (session('success'))
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{ session('success') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    @endif

    <table class="table table-hover data-table">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Nama Kelas</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>

        </tbody>
    </table>
</div>

@push('script')
<script type="text/javascript">
    $(function () {
      
      var table = $('.data-table').DataTable({
          processing: true,
          serverSide: true,
          ajax: "{{ route('kelas.index') }}",
          columns: [
              {data: 'id', name: 'id'},
              {data: 'nama', name: 'nama'},
              {data: 'action', name: 'action', orderable: false, searchable: false},
          ]
      });
      
    });
</script>
@endpush
@endsection